# Generated by Django 3.2.4 on 2021-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0003_alter_post_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagine_post1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
