# Generated by Django 3.2.4 on 2021-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0005_auto_20210702_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
